try {
    let result = somedefinedvariable + 5;
} catch(error) {
    console.log("An error ocured:", error.message);
}